### PR TITLE
Body expression supported

### LINKED ISSUE #27: The tool doesn't work with method body expressions
Currently, only following function syntax is supprorted: 
```kotlin
fun doSmth() {
    return act()
}
```

Following should be supported as well: 
```kotlin
fun doSmth() = act()
```

### PR DESCRIPTION
**Pull request by raipc**
Resolves #27 

The following tests fail because of new found refactorings:

https://github.com/JetBrains/kotless/commit/d396ad3df39bcea35398a807833323929422734f

```
the following elements were unexpected:
  ["Add Parameter type : DSLType in method public hasDependency(project Project, type DSLType) from class io.kotless.plugin.gradle.utils.Dependencies",
    "Rename Method public hasKtorDependency(project Project) renamed to public hasDependency(project Project, type DSLType) in class io.kotless.plugin.gradle.utils.Dependencies",
    "Add Parameter type : DSLType in method public getDependency(project Project, type DSLType) from class io.kotless.plugin.gradle.utils.Dependencies",
    "Rename Method public getKtorDependency(project Project) renamed to public getDependency(project Project, type DSLType) in class io.kotless.plugin.gradle.utils.Dependencies"]
```

https://github.com/JetBrains/kotless/commit/0be03b9e8500424f3d1ed8dd006bb4f46c255c90

```
the following elements were unexpected:
  ["Change Parameter Type entity : Webapp.ApiGateway.Deployment to entity : Application.ApiGateway.Deployment in method public mayRun(entity Application.ApiGateway.Deployment, context GenerationContext) in class io.kotless.gen.factory.apigateway.DeploymentFactory",
    "Change Parameter Type entity : Webapp.ApiGateway.DynamicRoute to entity : Application.ApiGateway.DynamicRoute in method public mayRun(entity Application.ApiGateway.DynamicRoute, context GenerationContext) in class io.kotless.gen.factory.route.dynamic.DynamicRouteFactory",
    "Change Parameter Type entity : Webapp.ApiGateway.StaticRoute to entity : Application.ApiGateway.StaticRoute in method public mayRun(entity Application.ApiGateway.StaticRoute, context GenerationContext) in class io.kotless.gen.factory.route.static.StaticRouteFactory",
    "Change Parameter Type entity : Webapp to entity : Application in method public mayRun(entity Application, context GenerationContext) in class io.kotless.gen.factory.route.static.StaticRoleFactory",
    "Change Parameter Type entity : Webapp.Route53 to entity : Application.Route53 in method public mayRun(entity Application.Route53, context GenerationContext) in class io.kotless.gen.factory.route53.CertificateFactory",
    "Change Parameter Type entity : Webapp.ApiGateway to entity : Application.ApiGateway in method public mayRun(entity Application.ApiGateway, context GenerationContext) in class io.kotless.gen.factory.apigateway.DomainFactory",
    "Change Parameter Type entity : Webapp.Route53 to entity : Application.Route53 in method public mayRun(entity Application.Route53, context GenerationContext) in class io.kotless.gen.factory.route53.RecordFactory"]

```

https://github.com/ktorio/ktor/commit/cb2cd6a4cdf05fcf9c27b7fbb6526cbf4922f371

```
the following elements were unexpected:
  ["Add Parameter module : SerialModule in method private buildSerializer(value Any, module SerialModule) : KSerializer<*> from class KotlinxSerializer.kt"]

```

https://github.com/ktorio/ktor/commit/41459eca6ce16fccc92f0318bcc93bd2022c263c

```
elements not found:
  ["Move Method public href(location Any) : String from class io.ktor.locations.Locations to public href(instance Any) : String from class io.ktor.locations.LocationsImpl",
    "Rename Parameter location : Any to instance : Any in method public href(instance Any) : String in class io.ktor.locations.LocationsImpl"]
and elements not expected:
  ["Move Method private getParameterNameFromAnnotation(parameter KParameter) : String from class io.ktor.locations.Locations to private getParameterNameFromAnnotation(parameter KParameter) : String from class io.ktor.locations.BackwardCompatibleImpl"]

```

https://github.com/ktorio/ktor/commit/4644d060756f33a8190af6ae2971e2937817608e

```
the following elements were unexpected:
  ["Add Parameter socketOptions : SocketOptions.TCPClientSocketOptions? in method internal attachForWritingDirectImpl(channel ByteChannel, nioChannel WritableByteChannel, selectable Selectable, selector SelectorManager, socketOptions SocketOptions.TCPClientSocketOptions?) : ReaderJob from class CIOWriter.kt",
    "Add Parameter socketOptions : SocketOptions.TCPClientSocketOptions? in method internal attachForReadingDirectImpl(channel ByteChannel, nioChannel ReadableByteChannel, selectable Selectable, selector SelectorManager, socketOptions SocketOptions.TCPClientSocketOptions?) : WriterJob from class CIOReader.kt",
    "Add Parameter requestData : HttpRequestData in method internal sendRequest(request ApacheRequestProducer, callContext CoroutineContext, requestData HttpRequestData) : HttpResponseData from class ApacheHttpRequest.kt",
    "Add Parameter requestData : HttpRequestData in method private toChannel(context CoroutineContext, requestData HttpRequestData) : ByteReadChannel from class OkHttpEngine.kt",
    "Change Parameter Type message : CURLMSG to message : CURLMSG? in method private readResponseDataFromEasyHandle(message CURLMSG?, easyHandle EasyHandle, result CURLcode) : CurlResponseData in class io.ktor.client.engine.curl.internal.CurlMultiApiHandler",
    "Add Parameter result : CURLcode in method private readResponseDataFromEasyHandle(message CURLMSG?, easyHandle EasyHandle, result CURLcode) : CurlResponseData from class io.ktor.client.engine.curl.internal.CurlMultiApiHandler",
    "Add Parameter requestData : HttpRequestData in method internal execute(request Request, requestData HttpRequestData) : Response from class OkUtils.kt"]

```

https://github.com/ktorio/ktor/commit/0bcdf147e596a15712335ba5c30ec3dd0b835dee

```
the following elements were unexpected:
  ["Rename Method public testIfModifiedSinceTimeZoned() renamed to public testIfModifiedSinceMultiple() : Unit in class io.ktor.tests.server.features.LastModifiedTest"]

```

### CODE REVIEW

File: kotlinrminer-cli/src/main/java/org/jetbrains/research/kotlinrminer/cli/decomposition/UMLOperationBodyMapper.java [hunk 1]
```diff
@@ -2774,9 +2774,9 @@ private String prepareConditional(String s) {
             conditional = s.substring(7, s.length() - 2);
         }
         int indexOfEquals = s.indexOf("=");
-        if (indexOfEquals > -1 && s.charAt(indexOfEquals + 1) != '=' && s.charAt(
-            indexOfEquals - 1) != '!' && s.endsWith(";\n")) {
-            conditional = s.substring(indexOfEquals + 1, s.length() - 2);
+        if (indexOfEquals > -1 && indexOfEquals < s.length() -1 &&
```
Comment (onewhl) [inline kotlinrminer-cli/src/main/java/org/jetbrains/research/kotlinrminer/cli/decomposition/UMLOperationBodyMapper.java]: Please, change it to `>= 0`

**Review by onewhl — APPROVED** [review]
